---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-app
  labels:
    app: kustomize-app
spec:
  type: LoadBalancer
  ports:
  - name: kustomize-app-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kustomize-app